image_size = 512
batch_size = 8
device = "cuda"
test = true
num_layers = 4
resnet_layers = 2
hidden_dim = 120
mlp_dim = 2048
num_heads = 12
dropout_rate = 0.1
patch_size = 32
num_patches = 256
num_channels = 3
patching_elements = 3072
final_resnet_output_dim = 2048
num_classes = 2
learning_rate = 0.0002
model_path = "models/vit2.pth"
data_dir = "dataset/"
num_epochs = 10
